name: 'todo'
title: ' To-Do '
enabled: True
interval: 0
height: 10
width: 85
y: 20
x: 2

save_path: 'widgets/save_file.txt'
max_rendering: 7  # adapt based on height, else it will cause buggy behaviour, use around height-3